# Created_by: 이호형
# Created_at: 20251015
# GitHub Actions Workflow 파일
# 깃허브 웹훅 만으로는 공인IP로 노출되지 않는 tekton에 접근할 수 없으므로
# 마스터 노드에 설치된 self-hosted runner가 job을 실행하도록
# 애플리케이션 깃 레파지토리에 GitHub Actions Workflow, Github Webhook 구성 필요
    # - 테크톤 이벤트리스너를 트리거링
    # - 파이프라인을 구동


# GitHub Actions 워크플로우 이름 (대시보드나 실행 이력에서 표시됨)
name: Trigger Tekton Eventlistener

# main 브랜치에 push가 발생할 때마다 이 워크플로우가 자동으로 실행
on:
  push:
    branches:
      - main


# 주요 필드 목록
# - clone_url: <애플리케이션 깃 레포 url>,
# - name: <레포명>
# - after: <???>


# 어떤 파이프라인 CR을 구동할 지에 대한 데이터를 줘야 된다.
# 파이프라인 커스텀리소스 명

# 파이프라인에 정의되어 있어 이미
# 깃 레포 URL
# 깃 레포명
# 브랜치명
# 하버 레지스트리 주소
# 하버 프로젝트명
# 이미지명
# 도커파일 경로


jobs:
  trigger:
    runs-on: self-hosted   # Job이 self-hosted runner 위에서 실행되도록 함 -> 테크톤 도메인이 공인이 아니므로 셀프 호스팅이 필요
    steps:
      - name: Trigger Tekton EventListener
      # 테크톤 이벤트리스너로 요청을 보내 파이프라인을 실행
        run: |
          curl -X POST http://ci-eventlistener.tg-cloud.co.kr/webhook/generic \
            -H "Content-Type: application/json" \
            -d '{
              "repo-url": "https://github.com/tg-cloud/tekton-eventlistener-webhook.git",
              "branch-name": "main",
              "pipeline-name": "tks-manual-spring-boot-pipeline-test"
            }'




